"""
workers/video_recorder.py — Module 4: Video Recorder
Uses Playwright to open the generated HTML site and record a video tour.
"""
import asyncio
import logging
from pathlib import Path

from sqlalchemy import select

from config import settings
from models import Lead
from database import AsyncSessionLocal

logger = logging.getLogger(__name__)


async def record_site_video(html_path: str, video_path: str, business_name: str) -> bool:
    """
    Open the generated site in a headless browser and record a video tour.
    Returns True on success, False on failure.
    """
    try:
        from playwright.async_api import async_playwright

        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)
            context = await browser.new_context(
                viewport={"width": 1280, "height": 720},
                record_video_dir=str(Path(video_path).parent),
                record_video_size={"width": 1280, "height": 720},
            )
            page = await context.new_page()

            # Load the generated HTML file
            file_url = f"file:///{Path(html_path).resolve().as_posix()}"
            await page.goto(file_url, wait_until="networkidle", timeout=30000)

            # Automated tour — slow scroll through the page
            await asyncio.sleep(2)  # Pause on hero section

            total_scroll = await page.evaluate("() => document.body.scrollHeight")
            scroll_steps = 10
            for i in range(1, scroll_steps + 1):
                y = int((i / scroll_steps) * total_scroll)
                await page.evaluate(f"window.scrollTo({{top: {y}, behavior: 'smooth'}})")
                await asyncio.sleep(0.8)

            await asyncio.sleep(1.5)  # Pause at bottom

            # Scroll back up
            await page.evaluate("window.scrollTo({top: 0, behavior: 'smooth'})")
            await asyncio.sleep(1)

            await context.close()
            await browser.close()

        # Playwright saves the video with an autogenerated name — rename it
        video_dir = Path(video_path).parent
        generated_videos = list(video_dir.glob("*.webm"))
        if generated_videos:
            latest = max(generated_videos, key=lambda p: p.stat().st_mtime)
            latest.rename(video_path)
            return True

        return False

    except ImportError:
        logger.warning("Playwright not installed. Using mock video generation.")
        return create_mock_video(video_path)
    except Exception as e:
        logger.error(f"Video recording failed: {e}")
        return False


def create_mock_video(video_path: str) -> bool:
    """Create a placeholder file when Playwright is not available."""
    Path(video_path).write_bytes(b"MOCK_VIDEO_PLACEHOLDER")
    return True


async def run_video_recording(job_id: int) -> int:
    """
    Step 4: Record video tours for all site-generated leads.
    Returns number of videos recorded.
    """
    logger.info(f"[Job {job_id}] Starting video recording")

    videos_dir = Path(settings.videos_dir)
    videos_dir.mkdir(parents=True, exist_ok=True)

    async with AsyncSessionLocal() as db:
        result = await db.execute(
            select(Lead).where(
                Lead.job_id == job_id,
                Lead.status == "site_generated",
            )
        )
        leads = result.scalars().all()
        lead_ids = [l.id for l in leads]

    recorded = 0

    for lead_id in lead_ids:
        async with AsyncSessionLocal() as db:
            result = await db.execute(select(Lead).where(Lead.id == lead_id))
            lead = result.scalar_one_or_none()
            if not lead or not lead.generated_site_path:
                continue

            video_path = str(videos_dir / f"lead_{lead_id}.webm")

            try:
                success = await record_site_video(
                    html_path=lead.generated_site_path,
                    video_path=video_path,
                    business_name=lead.business_name,
                )
                if success:
                    lead.video_path = video_path
                    lead.status = "video_recorded"
                    recorded += 1
                else:
                    lead.status = "failed"
                    lead.error_message = "Video recording produced no output"

            except Exception as e:
                logger.error(f"[Job {job_id}] Video recording failed for lead {lead_id}: {e}")
                lead.status = "failed"
                lead.error_message = f"Video recording error: {str(e)}"

            await db.commit()

    logger.info(f"[Job {job_id}] Video recording complete — {recorded} videos recorded")
    return recorded
